jhps_main_app/urls.py
from django.urls import path
from  . import views



app_name = 'jhps_main_app'
urlpatterns = [
    path("", views.index),
    path('contactUs/', views.contactUs, name='contactUs'),
    path('StudentEnquiryForm/', views.StudentEnquiry, name='StudentEnquiry'),
    path('ApplyJob/', views.Applyjob, name='Applyjob'),
    # Pages
    path('about', views.aboutUs, name='aboutUs'),
    path('vision_mission', views.vision_mission, name='vision_mission'),
    path('awards', views.awards, name='awards'),
    path('SMCommittee', views.SMCommittee, name='SMCommittee'),
    
    path('campus', views.campus, name='campus'),
    path('ClassRoom', views.ClassRoom, name='ClassRoom'),
    path('Laboratories', views.Laboratories, name='Laboratories'),
    path('Auditorium', views.Auditorium, name='Auditorium'),
    path('Library', views.Library, name='Library'),
    path('Safety', views.Safety, name='Safety'),
    path('InformaryRoom', views.InformaryRoom, name='InformaryRoom'),
    path('Canteen', views.Canteen, name='Canteen'),
    path('TeacherWelfare', views.TeacherWelfare, name='TeacherWelfare'),

    path('admissions', views.admissions, name='admissions'),
    path('FeeStructure', views.FeeStructure, name='FeeStructure'),

    path('academics', views.academics, name='academics'),
    path('LearningProcess', views.LearningProcess, name='LearningProcess'),
    path('ELearning', views.ELearning, name='ELearning'),
    path('CurriculumSyllabus', views.CurriculumSyllabus, name='CurriculumSyllabus'),
    path('SchoolTimings', views.SchoolTimings, name='SchoolTimings'),
    path('Faculty', views.Faculty, name='Faculty'),
 
    path('sportsCSA', views.sportsCSA, name='sportsCSA'),
    path('CarromBoard', views.CarromBoard, name='CarromBoard'),
    path('Chess', views.Chess, name='Chess'),
    path('Badminton', views.Badminton, name='Badminton'),
    path('TableTennis', views.TableTennis, name='TableTennis'),
    path('FootBall', views.FootBall, name='FootBall'),
    path('Cricket', views.Cricket, name='Cricket'),
    path('ThrowBall', views.ThrowBall, name='ThrowBall'),
    path('Tennis', views.Tennis, name='Tennis'),
    path('VolleyBall', views.VolleyBall, name='VolleyBall'),
    path('Kabaddi', views.Kabaddi, name='Kabaddi'),
    path('KoKo', views.KoKo, name='KoKo'),
    path('CSA', views.CSA, name='CSA'),
    path('ECA', views.ECA, name='ECA'),
    path('HouseAactivities', views.HouseAactivities, name='HouseAactivities'),
    path('EducationalTours', views.EducationalTours, name='EducationalTours'),

    path('careers', views.careers, name='careers'),
    path('circulars', views.circulars, name='circulars'),
    path('downloads', views.downloads, name='downloads'),
    path('transport', views.transport, name='transport'),
    path('gallery', views.gallery, name='gallery'),
    path('<int:id>/', views.galleryDetail, name='galleryDetail'),
    path('noticeboard', views.noticeboard, name='noticeboard'),
    path('events', views.events, name='events'),
    path('<int:id>/', views.eventDetail, name='eventDetail'),
    path('videogallery', views.videogallery, name='videogallery'),
    
    path('uc', views.uc, name='uc'),
]

jhps_web/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include('jhps_main_app.urls')),
    # path("", views.index),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)






admin.site.site_header = "Jubilee Hills Public School, Rampally"
admin.site.site_title = "Jubilee Hills Public School, Rampally"
admin.site.index_title = "Jubilee Hills Public School, Rampally Portal"

jhps_main_app/models.py
from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField
from phonenumber_field.modelfields import PhoneNumberField
from .validators import validate_file_size
# Create your models here.


class Admission_Enquiry (models.Model):
    enq_name = models.CharField(max_length=255)
    mobile_No = PhoneNumberField()
    email = models.EmailField(max_length=255)
    message = models.CharField (null=True, blank=True, max_length=255)

class Student_Enquiry (models.Model):
    year1 = 0
    year2 = 1
    YEAR_CHOICES = [(year1, '2022-23'), (year2, '2023-24')]
    academic_year = models.IntegerField(null=True, blank=True, choices=YEAR_CHOICES)
    first_name = models.CharField(null=True, blank=True, max_length=100)
    middle_name = models.CharField(null=True, blank=True, max_length=100)
    last_name = models.CharField(null=True, blank=True, max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    GENDER_MALE = 0
    GENDER_FEMALE = 1
    GENDER_CHOICES = [(GENDER_MALE, 'Male'), (GENDER_FEMALE, 'Female')]
    gender = models.IntegerField(null=True, blank=True, choices=GENDER_CHOICES)
    ch1 = 0
    ch2 = 1
    REL_CHOICES = [(ch1, 'FATHER'), (ch2, 'MOTHER')]
    relation = models.IntegerField(null=True, blank=True, choices=REL_CHOICES)
    L1 = 0
    L2 = 1 
    LOCAL_CHOICES = [(L1, 'Local'), (L2, 'Non-Local')]
    local_type = models.IntegerField(null=True, blank=True, choices=LOCAL_CHOICES)
    transfer_from = models.CharField(null=True, blank=True, max_length=150)
    mobile_No = PhoneNumberField(null=True, blank=True, max_length=50)
    email = models.EmailField(null=True, blank=True, max_length=150)
    message = models.TextField(null=True, blank=True, max_length=500)
    mother_name = models.CharField(null=True, blank=True, max_length=150)
    mother_organization = models.CharField(null=True, blank=True, max_length=150)
    mother_designation = models.CharField(null=True, blank=True, max_length=50)
    mother_income = models.CharField(null=True, blank=True, max_length=12)
    mother_mobile_No = PhoneNumberField(null=True, blank=True, max_length=50)
    mother_email = models.EmailField(null=True, blank=True, max_length=150)
    father_name = models.CharField(null=True, blank=True, max_length=150)
    father_orgnization = models.CharField(null=True, blank=True, max_length=150)
    father_designation = models.CharField(null=True, blank=True, max_length=50)
    father_income = models.CharField(null=True, blank=True, max_length=12)
    father_mobile_No = PhoneNumberField(null=True, blank=True, max_length=50)
    father_email = models.EmailField(null=True, blank=True, max_length=150)
    reference_name = models.CharField(null=True, blank=True, max_length=150)
    reference_designation = models.CharField(null=True, blank=True, max_length=50)
    reference_department = models.CharField(null=True, blank=True, max_length=50)
    reference_company = models.CharField(null=True, blank=True, max_length=50)
    reference_mobile_No = PhoneNumberField(null=True, blank=True, max_length=50)
    reference_email = models.EmailField(null=True, blank=True, max_length=150)
    remarks = models.TextField(null=True, blank=True, max_length=500)



class ApplyJob (models.Model):
   
    Post_Applying_For = models.CharField(max_length=150)
    Name_of_the_Candidate = models.CharField(max_length=100)
    Residential_Address = models.CharField(max_length=255)
    Own_house_rented = models.CharField(max_length=50)
    Mother_Tongue = models.CharField(max_length=25)
    date_of_birth = models.DateField()
    g1, g2, g3, g4, g5, g6 = 0,1,2,3,4,5
    CATEGORY_CHOICES = [(g1, 'SC'), (g2, 'ST'), (g3, 'BC'), (g4, 'OBC'), (g5, 'General'), (g6, 'Others')]
    Caste_Category_Religion = models.IntegerField(choices=CATEGORY_CHOICES)
    Email_ID = models.EmailField(max_length=150)
    Telephone_No = PhoneNumberField()
    Qualifications = models.CharField(max_length=150)
    Last_Worked  = models.CharField(null=True, blank=True, max_length=150)
    Reasons = models.CharField(null=True, blank=True, max_length=150)
    Any_friends = models.CharField(null=True, blank=True, max_length=50)
    Have_you_worked  = models.CharField(null=True, blank=True, max_length=12)
    Present_Salary = models.CharField(null=True, blank=True, max_length=10)
    Expected_Salary = models.CharField(null=True, blank=True, max_length=10)
    c1 = models.CharField(null=True, blank=True, max_length=55) 
    c2 = models.CharField(null=True, blank=True, max_length=55) 
    c3 = models.CharField(null=True, blank=True, max_length=55) 
    c4 = models.CharField(null=True, blank=True, max_length=55) 
    c5 = models.CharField(null=True, blank=True, max_length=55) 
    c6 = models.CharField(null=True, blank=True, max_length=55) 
    nsc1 = models.CharField(null=True, blank=True, max_length=100) 
    nsc2 = models.CharField(null=True, blank=True, max_length=100) 
    nsc3 = models.CharField(null=True, blank=True, max_length=100) 
    nsc4 = models.CharField(null=True, blank=True, max_length=100) 
    nsc5 = models.CharField(null=True, blank=True, max_length=100) 
    nsc6 = models.CharField(null=True, blank=True, max_length=100) 
    u1 = models.CharField(null=True, blank=True, max_length=100) 
    u2 = models.CharField(null=True, blank=True, max_length=100) 
    u3 = models.CharField(null=True, blank=True, max_length=100) 
    u4 = models.CharField(null=True, blank=True, max_length=100) 
    u5 = models.CharField(null=True, blank=True, max_length=100) 
    u6 = models.CharField(null=True, blank=True, max_length=100) 
    pos1 = models.CharField(null=True, blank=True, max_length=50) 
    pos2 = models.CharField(null=True, blank=True, max_length=50) 
    pos3 = models.CharField(null=True, blank=True, max_length=50) 
    pos4 = models.CharField(null=True, blank=True, max_length=50) 
    pos5 = models.CharField(null=True, blank=True, max_length=50) 
    pos6 = models.CharField(null=True, blank=True, max_length=50) 
    yp1 = models.CharField(null=True, blank=True, max_length=10) 
    yp2 = models.CharField(null=True, blank=True, max_length=10) 
    yp3 = models.CharField(null=True, blank=True, max_length=10) 
    yp4 = models.CharField(null=True, blank=True, max_length=10) 
    yp5 = models.CharField(null=True, blank=True, max_length=10) 
    yp6 = models.CharField(null=True, blank=True, max_length=10)
    m1 = models.CharField(null=True, blank=True, max_length=10) 
    m2 = models.CharField(null=True, blank=True, max_length=10) 
    m3 = models.CharField(null=True, blank=True, max_length=10) 
    m4 = models.CharField(null=True, blank=True, max_length=10) 
    m5 = models.CharField(null=True, blank=True, max_length=10) 
    m6 = models.CharField(null=True, blank=True, max_length=10)
    rc1 = models.CharField(null=True, blank=True, max_length=10) 
    rc2 = models.CharField(null=True, blank=True, max_length=10) 
    rc3 = models.CharField(null=True, blank=True, max_length=10) 
    rc4 = models.CharField(null=True, blank=True, max_length=10) 
    rc5 = models.CharField(null=True, blank=True, max_length=10) 
    rc6 = models.CharField(null=True, blank=True, max_length=10)
    sec1 = models.CharField(null=True, blank=True, max_length=10) 
    sec2 = models.CharField(null=True, blank=True, max_length=10) 
    sec3 = models.CharField(null=True, blank=True, max_length=10) 
    sec4 = models.CharField(null=True, blank=True, max_length=10) 
    sec5 = models.CharField(null=True, blank=True, max_length=10) 
    sec6 = models.CharField(null=True, blank=True, max_length=10)
    no1 = models.CharField(null=True, blank=True, max_length=100) 
    no2 = models.CharField(null=True, blank=True, max_length=100) 
    no3 = models.CharField(null=True, blank=True, max_length=100) 
    no4 = models.CharField(null=True, blank=True, max_length=100) 
    no5 = models.CharField(null=True, blank=True, max_length=100) 
    no6 = models.CharField(null=True, blank=True, max_length=100)
    deg1 = models.CharField(null=True, blank=True, max_length=100) 
    deg2 = models.CharField(null=True, blank=True, max_length=100) 
    deg3 = models.CharField(null=True, blank=True, max_length=100) 
    deg4 = models.CharField(null=True, blank=True, max_length=100) 
    deg5 = models.CharField(null=True, blank=True, max_length=100) 
    deg6 = models.CharField(null=True, blank=True, max_length=100)
    yow1 = models.CharField(null=True, blank=True, max_length=10) 
    yow2 = models.CharField(null=True, blank=True, max_length=10) 
    yow3 = models.CharField(null=True, blank=True, max_length=10) 
    yow4 = models.CharField(null=True, blank=True, max_length=10) 
    yow5 = models.CharField(null=True, blank=True, max_length=10) 
    yow6 = models.CharField(null=True, blank=True, max_length=10)
    sal1 = models.CharField(null=True, blank=True, max_length=10) 
    sal2 = models.CharField(null=True, blank=True, max_length=10) 
    sal3 = models.CharField(null=True, blank=True, max_length=10) 
    sal4 = models.CharField(null=True, blank=True, max_length=10) 
    sal5 = models.CharField(null=True, blank=True, max_length=10) 
    sal6 = models.CharField(null=True, blank=True, max_length=10)
    skill1 = models.CharField(null=True, blank=True, max_length=100)
    skill2 = models.CharField(null=True, blank=True, max_length=100)
    Sp_Name = models.CharField(null=True, blank=True, max_length=100)
    Sp_DOB = models.DateField(null=True, blank=True)
    Sp_Qul = models.CharField(null=True, blank=True, max_length=50)
    Sp_Occ = models.CharField(null=True, blank=True, max_length=50)
    Sp_Deg = models.CharField(null=True, blank=True, max_length=50)
    Sp_Inc = models.CharField(null=True, blank=True, max_length=10)
    F_Name = models.CharField(null=True, blank=True, max_length=100)
    F_DOB = models.DateField(null=True, blank=True)
    F_Qul = models.CharField(null=True, blank=True, max_length=50)
    F_Occ = models.CharField(null=True, blank=True, max_length=50)

jhps_main_app/templates/CarromBoard.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="main-box">


   <div class="pgf-cont">
     
   </div>
  
  
</div>
<script>
	let navDD = document.getElementsByClassName("actNav");
	for (let i = 0; i < navDD.length; i++) {
		navDD[i].className = navDD[i].className.replace(" active", "");
	}
	navDD[10].className += " active";
	let navDi = document.getElementsByClassName("dropdown-item");
	for (let i = 0; i < navDi.length; i++) {
		navDi[i].className = navDi[i].className.replace(" active", "");
	}
	navDi[25].className += " active";
	
 </script>
{% endblock %}

jhps_main_app/templates/EnquiryForm.html
{% extends "base.html" %}
{% block content %}
<div class="form_box">
<h1>Admission Enquiry</h1>
<div class="form_box_inn">
{% if submitted %}
<h1 style="background-color: green; color: yellow;">We Received your details.....</h1>
{% else %}
<form action="" method="POST">
    {% csrf_token %}          
    {{ form.as_p }}
    <input type="submit" value="Submit" class="btn btn-success">  
</form>
{% endif %}
</div>
</div>
<br><br>
{% endblock %}

jhps_main_app/templates/FeeStructure.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="main-box">
<h1>Fee Structure</h1>

   <img width="100%" src="{% static 'images/fee.png' %}"  alt="Logo JHPS">
</div>
<script>
   let navDD = document.getElementsByClassName("actNav");
   for (let i = 0; i < navDD.length; i++) {
       navDD[i].className = navDD[i].className.replace(" active", "");
   }
   navDD[0].className += " active";
   navDD[8].className += " active";

</script>
{% endblock %}

jhps_main_app/templates/applyjob.html
{% extends "base.html" %}
{% block content %}
<style>
    .tblh th, .sln{
        text-align: center;
        border: 1px solid rgb(226, 225, 225);
        
    }
    @media only screen and (max-width:600px) {
       #id_Sp_Name,#id_M_Name,#id_F_Name,#id_Sp_DOB,#id_Sp_DOB,#id_Sp_DOB,#id_C1_Name,#id_C2_Name,#id_C2_PSN,#id_C2_PSN #id_no1, #id_no2, #id_no3, #id_no4, #id_no5, #id_no6,#id_nsc1, #id_nsc2, #id_nsc3, #id_nsc4, #id_nsc5, #id_nsc6, #id_c1, #id_c2, #id_c3, #id_c4, #id_c5, #id_c6,#id_u1, #id_u2, #id_u3, #id_u4, #id_u5, #id_u6, #id_pos1, #id_pos2, #id_pos3, #id_pos4, #id_pos5, #id_pos6{
             width: 150px;
         }
    .form_box_inn{
        padding: 0;
        margin: 0;
    }
    }
</style>
<div class="form_box" style="width: 100%;">
    <h1>ADMINISTRATION PERSONAL DATA SHEET </h1>
    <div class="form_box_inn" style="width: 100%;">
        {% if submitted %}
        <h1 style="background-color: green; color: yellow;" >We Received your details.....</h1>
        {% else %}
        <form action="" method="POST">
            {% csrf_token %}
            <div class="form_box_inn2">

                <p>{{ form.Post_Applying_For }}</p>
                <p>{{ form.Name_of_the_Candidate }}</p>
                <p>{{ form.Residential_Address }}</p>
                <p>{{ form.Own_house_rented }}</p>
                <p>{{ form.Mother_Tongue }}</p>
                <span> Date of Birth</span>
                <p>{{ form.date_of_birth }}</p>
                <p style="color: rgb(63, 63, 63);">Caste Category /Religion : {{ form.Caste_Category_Religion }}</p>
                <p>{{ form.Email_ID }}</p>
                <p>{{ form.Telephone_No }}</p>
                <p>{{ form.Qualifications }}</p>
                <p>{{ form.Last_Worked }}</p>
                <p>{{ form.Reasons }}</p>
                <p>{{ form.Any_friends }}</p>
                <p>{{ form.Have_you_worked }}</p>
                <p>{{ form.Present_Salary }}</p>
                <p>{{ form.Expected_Salary }}</p>
            </div>
            <div class="form_box2">
                <h1>EDUCATIONAL & PROFESSIONAL QUALIFICATIONS – (10th Grade to Final Certification)</h1>
                <div class="form_box_inn3">
                    <table>
                        <tr class="tblh">
                            <th>SlNo</th>
                            <th>Course</th>
                            <th>Name of the School / College</th>
                            <th>University / Board</th>
                            <th>Place of Study</th>
                            <th>Year of Passing</th>
                            <th>Medium</th>
                            <th>Regular
                                / Correspondence
                            </th>
                            <th>% Secured</th>
                        </tr>
                        <tr>
                            <td class="sln">1</td>
                            <td>{{ form.c1 }}</td>
                            <td>{{ form.nsc1 }}</td>
                            <td>{{ form.u1 }}</td>
                            <td>{{ form.pos1 }}</td>
                            <td>{{ form.yp1 }}</td>
                            <td>{{ form.m1 }}</td>
                            <td>{{ form.rc1 }}</td>
                            <td>{{ form.sec1 }}</td>
                        </tr>
                        <tr>
                            <td class="sln">2</td>
                            <td>{{ form.c2 }}</td>
                            <td>{{ form.nsc2 }}</td>
                            <td>{{ form.u2 }}</td>
                            <td>{{ form.pos2 }}</td>
                            <td>{{ form.yp2 }}</td>
                            <td>{{ form.m2 }}</td>
                            <td>{{ form.rc2 }}</td>
                            <td>{{ form.sec2 }}</td>
                        </tr>
                        <tr>
                            <td class="sln">3</td>
                            <td>{{ form.c3 }}</td>
                            <td>{{ form.nsc3 }}</td>
                            <td>{{ form.u3 }}</td>
                            <td>{{ form.pos3 }}</td>
                            <td>{{ form.yp3 }}</td>
                            <td>{{ form.m3 }}</td>
                            <td>{{ form.rc3 }}</td>
                            <td>{{ form.sec3 }}</td>
                        </tr>
                        <tr>
                            <td class="sln">4</td>
                            <td>{{ form.c4 }}</td>
                            <td>{{ form.nsc4 }}</td>
                            <td>{{ form.u4 }}</td>
                            <td>{{ form.pos4 }}</td>
                            <td>{{ form.yp4 }}</td>
                            <td>{{ form.m4 }}</td>
                            <td>{{ form.rc4 }}</td>
                            <td>{{ form.sec4 }}</td>
                        </tr>
                        <tr>
                            <td class="sln">5</td>
                            <td>{{ form.c5 }}</td>
                            <td>{{ form.nsc5 }}</td>
                            <td>{{ form.u5 }}</td>
                            <td>{{ form.pos5 }}</td>
                            <td>{{ form.yp5 }}</td>
                            <td>{{ form.m5 }}</td>
                            <td>{{ form.rc5 }}</td>
                            <td>{{ form.sec5 }}</td>
                        </tr>
                        <tr>
                            <td class="sln">6</td>
                            <td>{{ form.c6 }}</td>
                            <td>{{ form.nsc6 }}</td>
                            <td>{{ form.u6 }}</td>
                            <td>{{ form.pos6 }}</td>
                            <td>{{ form.yp6 }}</td>
                            <td>{{ form.m6 }}</td>
                            <td>{{ form.rc6 }}</td>
                            <td>{{ form.sec6 }}</td>
                        </tr>

                    </table>
                </div>
            </div>

            <div class="form_box2">
                <h1>WORK EXPERIENCE </h1>
                <div class="form_box_inn3">
                    <table>
                        <tr class="tblh">
                            <th>SlNo</th>
                            <th>Name of the organization</th>
                            <th>Designation</th>
                            <th>Years of work</th>
                            <th>Last Salary Drawn</th>
                        </tr>
                        <tr>
                            <td class="sln">1</td>
                            <td>{{ form.no1 }}</td>
                            <td>{{ form.deg1 }}</td>
                            <td>{{ form.yow1 }}</td>
                            <td>{{ form.sal1 }}</td>
                        </tr>

                        <tr>
                            <td class="sln">2</td>
                            <td>{{ form.no2 }}</td>
                            <td>{{ form.deg2 }}</td>
                            <td>{{ form.yow2 }}</td>
                            <td>{{ form.sal2 }}</td>
                        </tr>
                        <tr>
                            <td class="sln">3</td>
                            <td>{{ form.no3 }}</td>
                            <td>{{ form.deg3 }}</td>
                            <td>{{ form.yow3 }}</td>
                            <td>{{ form.sal3 }}</td>
                        </tr>
                        <tr>
                            <td class="sln">4</td>
                            <td>{{ form.no4 }}</td>
                            <td>{{ form.deg4 }}</td>
                            <td>{{ form.yow4 }}</td>
                            <td>{{ form.sal4 }}</td>
                        </tr>
                        <tr>
                            <td class="sln">5</td>
                            <td>{{ form.no5 }}</td>
                            <td>{{ form.deg5 }}</td>
                            <td>{{ form.yow5 }}</td>
                            <td>{{ form.sal5 }}</td>
                        </tr>
                        <tr>
                            <td class="sln">6</td>
                            <td>{{ form.no6 }}</td>
                            <td>{{ form.deg6 }}</td>
                            <td>{{ form.yow6 }}</td>
                            <td>{{ form.sal6 }}</td>
                        </tr>

                    </table>
                </div>
            </div>


            <div class="form_box2">
                <h1>SPECIAL SKILLS, IF ANY </h1>
                <div class="form_box_inn3">
                    <table>
                        <tr>
                            <td class="sln">1</td>
                            <td style="width: 100%;">{{ form.skill1 }}</td>
                        </tr>
                        <tr>
                            <td class="sln">2</td>
                            <td style="width: 100%;">{{ form.skill2 }}</td>
                        </tr>
                    </table>
                </div>
            </div>

            <div class="form_box2">
                <h1>FAMILY DATA</h1>
                <div class="form_box_inn3">
                    <table>
                        <tr class="tblh">
                            <th>Family Members</th>
                            <th>Name</th>
                            <th>Date of Birth</th>
                            <th>Highest / Special Qualification</th>
                            <th>Occupation &
                                Company Name
                                </th>
                            <th>Designation</th>
                            <th>Annual income</th>
                        </tr>
                        <tr>
                            <td class="sln">Spouse</td>
                            <td>{{ form.Sp_Name }}</td>
                            <td>{{ form.Sp_DOB }}</td>
                            <td>{{ form.Sp_Qul }}</td>
                            <td>{{ form.Sp_Occ }}</td>
                            <td>{{ form.Sp_Deg }}</td>
                            <td>{{ form.Sp_Inc }}</td>
                        </tr>
                        <tr>
                            <td class="sln">Father</td>
                            <td>{{ form.F_Name }}</td>
                            <td>{{ form.F_DOB }}</td>
                            <td>{{ form.F_Qul }}</td>
                            <td>{{ form.F_Occ }}</td>
                            <td>{{ form.F_Deg }}</td>
                            <td>{{ form.F_Inc }}</td>
                        </tr>
                        <tr>
                            <td class="sln">Mother</td>
                            <td>{{ form.M_Name }}</td>
                            <td>{{ form.M_DOB }}</td>
                            <td>{{ form.M_Qul }}</td>
                            <td>{{ form.M_Occ }}</td>
                            <td>{{ form.M_Deg }}</td>
                            <td>{{ form.M_Inc }}</td>
                        </tr>
                    </table>
                </div>
            </div>


            <div class="form_box2">
                <h1>CHILDREN DATA </h1>
                <div class="form_box_inn3">
                    <table>
                        <tr class="tblh">
                            <th>No</th>
                            <th>Name</th>
                            <th>Date of Birth</th>
                            <th>Class Studying</th>
                            <th>Present school name</th>
                        </tr>
                        <tr>
                            <td class="sln">1</td>
                            <td>{{ form.C1_Name}}</td>
                            <td>{{ form.C1_DOB }}</td>
                            <td>{{ form.C1_St  }}</td>
                            <td>{{ form.C1_PSN }}</td>
                        </tr>

                        <tr>
                            <td class="sln">2</td>
                            <td>{{ form.C2_Name}}</td>
                            <td>{{ form.C2_DOB }}</td>
                            <td>{{ form.C2_St  }}</td>
                            <td>{{ form.C2_PSN }}</td>
                        </tr>
                    </table>
                </div>
            </div>

            
            <div class="form_box2">
                <h1>REFERENCES </h1>
               
                    <table>
                        <tr>
                            <th>1. Name, Address & Contact No</th>
                            <th>2. Name, Address & Contact No</th>
                        </tr>
                        <tr>
                            <td>{{ form.Ref1}}</td>
                            <td>{{ form.Ref2}}</td>
                        
                        </tr>
                    </table>
          
            </div>

            
            <div class="form_box2">
                <h1>UPLOAD YOUR RECENT RESUME</h1>
                <div class="form_box_inn3">
                    <p>{{ form.upload_cv }}</p>
                </div>
            </div>

<br>



            <input type="submit" value="Submit" class="btn btn-success"><br>
        </form>
        {% endif %}
    </div>
</div>
<br><br>

<script>
    let sd = document.getElementsByTagName('select');
    for (let i of sd){
        i.setAttribute('class', 'form-select');
    }
</script>
{% endblock %}